bool p(int,int,int,int);
bool change_gate();
bool change_block();
void draw(bool,bool,bool);
bool nadpis(string,int,int);
void wires();
void gates();
void guns();
void lasers();
void holes();
void rocks();
void portals();
void bullets();
void set_camera(unsigned short,unsigned short,bool);
bool gin(uint8_t* c);
bool gin(int* c);
void subtitres();
void open(string);
void save(string);
void action();
void keys();
char in(ifstream& in);
char in(stringstream& in);
void open_old(string);
void create_laser(uint8_t x,uint8_t y,uint8_t n);
bool inputwh(string,uint8_t,uint8_t);
bool console();
SDL_Surface *create_surface(int width,int height);
int get_level_c(int w,int h);
void minimap();
void game_init(bool restart);
string command(string);
uint8_t input_number(uint8_t);
bool pause();
bool end(bool,bool);
void go();
void achievements();
bool in_range(int,int,int);
int test(int,int);
vector<vector<uint8_t>> maze_generate(int w,int h);
uint8_t lidtoln(string lid);
string lntolid(uint8_t ln);
string postlid(string lid);
bool editor();
stringstream RWstream(const char *filename);
char *RWget(const char *filename);
void sensor_draw();
void destroy_subt();
int main(int argv,char **argc);
bool Back();
void load_subtitles();
